// Code generated by protoc-gen-rest-client. DO NOT EDIT.
// source: proto/ports/output/request.proto

package students

import (
	"encoding/json"
	"github.com/go-playground/validator/v10"
	"github.com/tecmise/connector-lib/pkg/ports/output/request"
)

// ImportStudentBySheetRequest representa o modelo de dados para ImportStudentBySheetRequest
type ImportStudentBySheetRequest struct {
	// The sheet ID
	SheetId int64 `json:"sheet_id" validate:"required"`
	// School ID
	SchoolId string `json:"school_id" validate:"required" sqs:"message_group_id"`
	// Deduplication key for SQS
	DeduplicationKey string `json:"deduplication_key" validate:"required" sqs:"message_deduplication_id"`
}

// String retorna uma representação em string do ImportStudentBySheetRequest
var _ request.Validatable = (*ImportStudentBySheetRequest)(nil)

func (m *ImportStudentBySheetRequest) String() string {
	data, _ := json.MarshalIndent(m, "", "  ")
	return string(data)
}

// Validate valida os campos do ImportStudentBySheetRequest
func (m *ImportStudentBySheetRequest) Validate(functions ...request.CustomValidator) error {
	validate := validator.New()
	if functions != nil {
		for _, function := range functions {
			if err := validate.RegisterValidation(function.Name, function.Method); err != nil {
				return err
			}
		}
	}
	return validate.Struct(m)
}

// NewImportStudentBySheetRequest cria uma nova instância de ImportStudentBySheetRequest
func NewImportStudentBySheetRequest() *ImportStudentBySheetRequest {
	return &ImportStudentBySheetRequest{}
}
