// Code generated by protoc-gen-rest-client. DO NOT EDIT.
// source: proto/adapters/outbound/publisher.proto

package mail

import (
	assync "github.com/tecmise/connector-lib/pkg/ports/output/assync"
	students "github.com/tecmise/student-sheet-job-connector-go/pkg/ports/output/students"
)

import (
	"context"
)
import (
	"github.com/tecmise/connector-lib/pkg/adapters/outbound/client_sqs"
	"github.com/tecmise/connector-lib/pkg/ports/output/request"
)

type (
	SheetImportPublisher interface {
		SendStudentSheet(ctx context.Context, req *students.ImportStudentBySheetRequest, validations ...request.CustomValidator) (*assync.QueueTriggerResponse, error)
	}

	sheetImportPublisher struct {
		publisher client_sqs.AssyncPublisher
	}
)

func NewSheetImportPublisher() SheetImportPublisher {
	return &sheetImportPublisher{
		publisher: client_sqs.NewAssyncPublisher(),
	}
}

func (i *sheetImportPublisher) SendStudentSheet(ctx context.Context, req *students.ImportStudentBySheetRequest, validations ...request.CustomValidator) (*assync.QueueTriggerResponse, error) {
	if err := request.ValidateObject(req, validations...); err != nil {
		return nil, err
	}
	return i.publisher.Publish(ctx, req, "student-sheet-queue", req.SchoolId, req.DeduplicationKey)
}
